<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

</body>
<script>
    // finally是什么?
    // finally是try catch 之后的一个代码块，作用是，无论try中是否出现异常，finally 中的代码都会执行


    function div(x, y) {
        if (y === 0) {
            // 除数不能为零，所以此处我们手动抛出异常
            // 1. 创建异常对象
            let error = new Error('除数不能为0')
            // 2. 抛出异常
            // 抛出异常后程序将终止运行
            throw error
        }
        return x / y
    }

    try {
        let r = div(3, 1)
        console.log(r);
    } catch (e) {
        console.error(e);
    } finally {
        // try catch 后 最终一定会执行的程序
        console.log('无论try执行成功还是抛出异常，都会执行此处的代码');
    }
</script>

</html>